NMH1000_Arduino: NMH1000_Arduino Class Reference
NMH1000_Arduino Class Reference
#include <NMH1000_Arduino.h>
Public Types
enum Mode { _I2C , _STDALONE }
Public Member Functions
uint8_t init ()
Initialize the device with reset with several GPIO pin configuration.
uint8_t init (bool pinconfig)
Initialize the device with reset.
void reset ()
Reset the device by writing CONTROL_REG1=0x01.
void threshold (uint8_t assert, uint8_t clear)
Set the threshold to output HIGH or LOW. Be sure assert is always smaller than clear.
void autorun (odr_freq odr)
Start autonomous mode by setting AUTO=0b01.
void autorun (odr_freq odr, uint8_t assert, uint8_t clear)
Start autonomous mode by setting AUTO=0b01 with threshold values.
int8_t read ()
Read magnetic field value. Only outputs HIGH or LOW when STANDALONE mode is selected.
NMH1000_Arduino (Mode mode)
NMH1000_Arduino (Mode mode, uint8_t i2c_address)
NMH1000_Arduino (Mode mode, TwoWire &wire, uint8_t i2c_address)
~NMH1000_Arduino ()
virtual float read (void)
bool ping (void)
int reg_w (uint8_t reg_adr, uint8_t *data, uint16_t size)
int reg_w (uint8_t reg_adr, uint8_t data)
int reg_r (uint8_t reg_adr, uint8_t *data, uint16_t size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
void write_r16 (uint8_t reg, uint16_t val)
uint8_t read_r8 (uint8_t reg)
uint16_t read_r16 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
void bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
Public Attributes
Mode mode
If STANDALONE mode is used, the device cannot be setup and read function returns only HIGH or LOW.
Detailed Description
Definition at line 32 of file NMH1000_Arduino.h.
Member Enumeration Documentation
Mode
enum NMH1000_Arduino::Mode
Enumerator
_I2C
_STDALONE
Definition at line 34 of file NMH1000_Arduino.h.
Constructor & Destructor Documentation
NMH1000_Arduino() [1/3]
NMH1000_Arduino::NMH1000_Arduino (Mode mode)
Create a NMH1000_Arduino instance
Parameters
mode Be selected from _I2C when I2C mode or _STDALONE when STANDALONE mode
Definition at line 15 of file NMH1000_Arduino.cpp.
NMH1000_Arduino() [2/3]
NMH1000_Arduino::NMH1000_Arduino (Mode mode, uint8_t i2c_address = NMH1000_DEVICE_ADDRESS)
Create a NMH1000_Arduino instance
Parameters
mode Be selected from _I2C when I2C mode or _STDALONE when STANDALONE mode
i2c_address I2C address for NMH1000. This does NOT change NMH1000 I2C address by writing register.
Definition at line 16 of file NMH1000_Arduino.cpp.
NMH1000_Arduino() [3/3]
NMH1000_Arduino::NMH1000_Arduino (Mode mode, TwoWire & wire, uint8_t i2c_address = NMH1000_DEVICE_ADDRESS)
Create a NMH1000_Arduino instance
Parameters
mode Be selected from _I2C when I2C mode or _STDALONE when STANDALONE mode
wire TwoWire instance
i2c_address I2C address for NMH1000. This does NOT change NMH1000 I2C address by writing register.
Definition at line 17 of file NMH1000_Arduino.cpp.
~NMH1000_Arduino()
NMH1000_Arduino::~NMH1000_Arduino ()
Destructor of FXLS89xx_Arduino
Definition at line 18 of file NMH1000_Arduino.cpp.
Member Function Documentation
autorun() [1/2]
void NMH1000_Arduino::autorun (odr_freq odr)
Start autonomous mode by setting AUTO=0b01.
Parameters
odr The ODR frequency selected from odr_freq.
Definition at line 48 of file NMH1000_Arduino.cpp.
autorun() [2/2]
void NMH1000_Arduino::autorun (odr_freq odr, uint8_t assert, uint8_t clear)
Start autonomous mode by setting AUTO=0b01 with threshold values.
Parameters
odr The ODR frequency selected from odr_freq.
assert The threshold to assert. Shall be smaller than clear.
clear The threshold to clear. Shall be bigger than assert.
Definition at line 54 of file NMH1000_Arduino.cpp.
bit_op16()
void NMH1000_Arduino::bit_op16 (uint8_t reg, uint16_t mask, uint16_t value)
bit_op8()
void NMH1000_Arduino::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
init() [1/2]
uint8_t NMH1000_Arduino::init ()
Initialize the device with reset with several GPIO pin configuration.
Returns
WHO_AM_I register value
Definition at line 20 of file NMH1000_Arduino.cpp.
Referenced by init().
init() [2/2]
uint8_t NMH1000_Arduino::init (bool pinconfig)
Initialize the device with reset.
Parameters
pinconfig If you wouldn't like to config the pins by this function, put false in this parameter. This parameter can be skipped.
Returns
WHO_AM_I register value
Definition at line 25 of file NMH1000_Arduino.cpp.
ping()
bool NMH1000_Arduino::ping (void)
Ping the device
Returns
true when ACK
read() [1/2]
int8_t NMH1000_Arduino::read ()
Read magnetic field value. Only outputs HIGH or LOW when STANDALONE mode is selected.
Returns
MAG_DATA value when I2C mode or output state when STANDALONE mode
Definition at line 61 of file NMH1000_Arduino.cpp.
read() [2/2]
virtual float NMH1000_Arduino::read (void) virtual
Get temperature value in degree Celsius [°C]
This method simply calls "temp()" method
Returns
temperature value in degree Celsius [°C]
read_r16()
uint16_t NMH1000_Arduino::read_r16 (uint8_t reg)
Register read, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
Returns
data value
read_r8()
uint8_t NMH1000_Arduino::read_r8 (uint8_t reg)
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Referenced by init(), and read().
reg_r() [1/2]
uint8_t NMH1000_Arduino::reg_r (uint8_t reg_adr)
Single register read
Parameters
reg register index/address/pointer
Returns
read data
reg_r() [2/2]
int NMH1000_Arduino::reg_r (uint8_t reg_adr, uint8_t * data, uint16_t size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reg_w() [1/2]
int NMH1000_Arduino::reg_w (uint8_t reg_adr, uint8_t * data, uint16_t size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Referenced by autorun(), autorun(), and threshold().
reg_w() [2/2]
int NMH1000_Arduino::reg_w (uint8_t reg_adr, uint8_t data)
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
reset()
void NMH1000_Arduino::reset ()
Reset the device by writing CONTROL_REG1=0x01.
Definition at line 36 of file NMH1000_Arduino.cpp.
Referenced by init().
threshold()
void NMH1000_Arduino::threshold (uint8_t assert, uint8_t clear)
Set the threshold to output HIGH or LOW. Be sure assert is always smaller than clear.
Parameters
assert The threshold to assert. Shall be smaller than clear.
clear The threshold to clear. Shall be bigger than assert.
Definition at line 42 of file NMH1000_Arduino.cpp.
Referenced by autorun().
write_r16()
void NMH1000_Arduino::write_r16 (uint8_t reg, uint16_t val)
Register write, 16 bit
This 16 bit access may ot be common but it's useful for sensor devices
Parameters
reg register index/address/pointer
val data value
write_r8()
void NMH1000_Arduino::write_r8 (uint8_t reg, uint8_t val)
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Referenced by reset().
Member Data Documentation
mode
Mode NMH1000_Arduino::mode
If STANDALONE mode is used, the device cannot be setup and read function returns only HIGH or LOW.
Definition at line 35 of file NMH1000_Arduino.h.
Referenced by autorun(), autorun(), init(), read(), reset(), and threshold().
The documentation for this class was generated from the following files:
NMH1000_Arduino.h
NMH1000_Arduino.cpp